### ISSUE TITLE
Importer chokes on nonexistent macrocounty entry

### ISSUE THREAD

**Issue by cag** [pelias/whosonfirst#174] opened 2016-12-02 23:12 UTC
Basically, the latest wof data has this issue:

https://github.com/whosonfirst-data/whosonfirst-data/issues/543

and it causes the importer to complain:

```
2016-12-02T22:00:44.373Z - info: [whosonfirst] Loading county records from /home/dev/pelias-data/whosonfirst/meta/wof-county-latest.csv
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/home/dev/pelias-data/whosonfirst/data/110/849/885/6/1108498856.geojson'
```

**Comment by missinglink** [comment] 2016-12-05 16:39
looks like this is due to the new id format, previously they were max 9 numbers, that one is 10 digits long.

**Comment by orangejulius** [comment] 2016-12-05 16:44
I have some code somewhere to handle the new ID format, I'll submit the PR today.

**Comment by orangejulius** [comment] 2016-12-06 20:23
Update: it appears that this is actually caused by an error in the WOF bundles. The whosonfirst importer uses the path from the meta files correctly. Here's a script that demonstrates the current issue:

```sh
#!/bin/bash -x

missing_id=1108498856

wget https://whosonfirst.mapzen.com/bundles/wof-macrocounty-latest.csv
grep $missing_id wof-macrocounty-latest.csv
wget https://whosonfirst.mapzen.com/bundles/wof-macrocounty-latest-bundle.tar.bz2
tar xf wof-macrocounty-latest-bundle.tar.bz2

find . -name "${missing_id}*"
```

**Comment by tylux** [comment] 2016-12-06 20:49
@orangejulius is there a workaround to start importing the WOF bundles? Or just sit tight until the issue is resolved? Thanks!

**Comment by orangejulius** [comment] 2016-12-06 21:16
Hey @tylux,
I'd recommend sitting for a bit, hopefully it will be fixed soon. If you really care about getting an import done more than data integrity, you can remove the line with that id in the `wof-macrocounty-latest.csv` file.

**Comment by orangejulius** [comment] 2016-12-08 14:55
Hey @tylux and @cag,
The WOF bundle has been fixed, if you get a chance try the importer again, everything should work.

**Comment by tylux** [comment] 2016-12-08 20:31
Hello @orangejulius seems to be fixed so far on the import.

**Comment by orangejulius** [comment] 2016-12-09 18:59
Great, glad it's fixed. The WOF importer intentionally fails loudly on any issue reading files (we just made it even stricter in https://github.com/pelias/whosonfirst/pull/178), so I'm closing this issue now. The memory leak is tracked in https://github.com/pelias/whosonfirst/issues/180 and hopefully we can fix that soon.

**Closed** 2016-12-09 19:00 UTC
Labels: outreach
