### ISSUE TITLE
null island postcodes being imported

### ISSUE THREAD

**Issue by missinglink** [pelias/whosonfirst#267] opened 2017-08-17 15:24 UTC
The following entry is being imported with a geometry of `POINT( 0, 0 )` and is being returned to the user as such:

```javascript
/v1/search/structured?postalcode=9490

{
  "geocoding": {
    "version": "0.2",
    "attribution": "https://search.mapzen.com/v1/attribution",
    "query": {
      "parsed_text": {
        "postalcode": "9490"
      },
      "size": 10,
      "private": false,
      "lang": {
        "name": "English",
        "iso6391": "en",
        "iso6393": "eng",
        "defaulted": false
      },
      "querySize": 20
    },
    "engine": {
      "name": "Pelias",
      "author": "Mapzen",
      "version": "1.0"
    },
    "timestamp": 1502983111936
  },
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          0,
          0
        ]
      },
      "properties": {
        "id": "538963963",
        "gid": "whosonfirst:postalcode:538963963",
        "layer": "postalcode",
        "source": "whosonfirst",
        "source_id": "538963963",
        "name": "9490",
        "postalcode": "9490",
        "postalcode_gid": "whosonfirst:postalcode:538963963",
        "confidence": 1,
        "match_type": "exact",
        "accuracy": "centroid",
        "label": "9490"
      },
      "bbox": [
        0,
        0,
        0,
        0
      ]
    }
  ],
  "bbox": [
    0,
    0,
    0,
    0
  ]
}
```

**Comment by missinglink** [comment] 2017-08-17 15:24
reported in https://github.com/pelias/pelias/issues/622#issuecomment-323057176

**Comment by orangejulius** [comment] 2018-03-27 16:54
Interesting, considering the code in https://github.com/pelias/whosonfirst/blob/master/src/components/isNotNullIslandRelated.js

Hopefully we are very close to a fix for this?

**Comment by missinglink** [comment] 2018-03-27 19:40
That code only checks for triple equals the string right? Isn't it possible for those values to also be floats?

**Comment by orangejulius** [comment] 2018-08-02 21:37
Dupe of https://github.com/pelias/pelias/issues/692

**Closed by orangejulius** 2018-08-02 21:37 UTC
